databases:
  - name: postfacto-db
    databaseName: postfacto
    user: postfacto
    plan: free

services:
  - type: web
    name: postfacto
    runtime: ruby
    rubyVersion: "3.3"
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postfacto-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: ACTION_CABLE_HOST
        sync: false
